## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np
#1 2*3 Matrix
a = np.array([[20,25,30],
                      [35,40,45]])
#2 3*2 Matrix
b = np.array([[0,5],
                      [10,15],
                      [20,25]])

In [16]:
c= np.dot(a,b)
c

array([[ 850, 1225],
       [1300, 1900]])

## Write a NumPy program to compute the determinant of a given square array

In [27]:
a = np.random.randint(1,10,(3,3))


In [26]:
print(a)
np.linalg.det(a)

[[2 6 4]
 [7 8 7]
 [6 6 1]]


117.99999999999993

## Write a NumPy program to compute the cross product of two given vectors

In [28]:
a = np.random.randint(1,10,3)
b = np.random.randint(1,10,3)
print ( a , b)

[4 1 1] [2 4 4]


In [29]:
c=np.cross(a,b)
c

array([  0, -14,  14])

## Write a NumPy program to compute the condition number of a given matrix

In [30]:
a = np.random.randint(1,10,(3,3))
a


array([[7, 8, 3],
       [8, 3, 9],
       [5, 6, 2]])

In [33]:
np.linalg.cond(a)

374.49442713870445

## Write a NumPy program to compute the inverse of a given matrix

In [34]:
a = np.random.randint(1,10,(4,4))
a


array([[7, 2, 6, 1],
       [9, 9, 7, 5],
       [9, 2, 2, 6],
       [5, 2, 9, 2]])

In [36]:
np.linalg.inv(a)

array([[ 0.24306077, -0.02850713,  0.03225806, -0.14703676],
       [-0.00825206,  0.15528882, -0.09677419, -0.09377344],
       [-0.05701425, -0.0180045 , -0.03225806,  0.17029257],
       [-0.34283571, -0.00300075,  0.16129032,  0.19504876]])